web/framework/backend/controllers/TestController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use backend\models\Apple;
use yii\filters\AccessControl;

/**
 * Контроллер для выполнения тестовой задачи
 */
class TestController extends Controller
{
    /**
     * Запрещаем вход неавторизированным
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Отображает список сгенерированных яблок
     */
    public function actionIndex()
    {
        return $this->render('index', ['apples'=>Apple::getAll()]);
    }

    /**
     * Добавляет яблоко
     */
    public function actionGenapple()
    {
        new Apple();

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['reload_page' => true];
    }

    /**
     * Удадяем все яблоки
     */
    public function actionDelall()
    {
        Apple::deleteAll();

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['reload_page' => true];
    }

    /**
     * Удадяем одно яблоко
     */
    public function actionDelone()
    {
        $idx = Yii::$app->request->post('idx', '');
        Apple::getOne($idx)->delete();

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['reload_page' => true];
    }

    /**
     * Упасть на землю
     */
    public function actionFalltoground()
    {
        $idx = Yii::$app->request->post('idx', '');
        Apple::getOne($idx)->fallToGround();

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['reload_page' => true];
    }

    /**
     * Откусить
     */
    public function actionEat()
    {
        $idx      = Yii::$app->request->post('idx', '');
        $size_eat = intval(Yii::$app->request->post('size_eat', 0));
        Apple::getOne($idx)->eat($size_eat);

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return ['reload_page' => true];
    }

}

web/framework/backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <style>
        #error_alert_top{
            display:none;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 9999;
        }
        #message_alert_top{
            display:none;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 9999;
        }
    </style>

</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Тест от prhol.ru',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Главная', 'url' => ['/site/index']],
    ];
    if (!Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Тестовая задача', 'url' => ['/test/index']];
    } 

    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<div class="alert alert-danger" id="error_alert_top" role="alert"></div>
<div class="alert alert-success" id="message_alert_top" role="alert"></div>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>